# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 19:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_group_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='posts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'data': []}, null=True),
        ),
    ]
