# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160409_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.CharField(max_length=300)),
                ('unsaveURL', models.CharField(max_length=310)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('body', models.TextField(blank=True, max_length=40000, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Group')),
            ],
        ),
    ]
